name: CI

on:
  push:
    branches: [ main, branch1 ]
  pull_request:
    branches: [ main, branch1 ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
      with: #recursively pulls submodules, like a google tes\t folder
        submodules: recursive

    # Here is how you run terminal commands using GitHub workflows
    - name: output some text to the terminal using echo
      run: echo I just ran the echo command in the terminal cool story bro

    #if you had a google test folder, and didnt do the recursive on checkout, mabe do this
    - name: update recurseivelu
      run: echo I just ran the echo command in the terminal cool story bro

    # Compile and run the Hello World program
    - name: Hello World
      run: |
       cmake .
       make
       ./HelloWorld

    #alternatively we could use cmake and make
  